USE ;
GO
DECLARE @START_DATE DATETIME
DECLARE @END_DATE DATETIME
SET @START_DATE = '01/01/2016'
SET @END_DATE = '12/31/2016'

SELECT
CAEMP.ID, CAEMP.SORT_NAME AS [PROVIDER NAME], COUNT (DISTINCT sv.[CLIENT_ID]) AS [COUNT OF CLIENTS]

FROM CDCLSVC sv
		LEFT JOIN CDCLIENT ON sv.CLIENT_ID = CDCLIENT.ID
				AND sv.[BEG_DATE] between @START_DATE AND @END_DATE AND
				ISNULL(VOID_FLAG,'')<>'Y' AND
				[CNTTYP_ID] = 'F' AND
				[APPTYP_ID] IN (1, 2) AND
				CDCLIENT.[DOB] BETWEEN DATEADD (YEAR, -17, sv.BEG_DATE) AND DATEADD (YEAR, -6, sv.BEG_DATE)
		LEFT JOIN CAEMP ON sv.EMP_ID = CAEMP.ID
		LEFT JOIN CDSVRCRD ON sv.EMP_ID = CDSVRCRD.EMP_ID
		LEFT JOIN CDCLDIAG ON CDCLDIAG.CLIENT_ID = CDCLIENT.ID
		LEFT JOIN CDCLINS ON CDCLINS.CLIENT_ID = CDCLIENT.ID

WHERE sv.[BEG_DATE] between @START_DATE AND @END_DATE AND
				ISNULL(VOID_FLAG,'')<>'Y' AND
				[CNTTYP_ID] = 'F' AND
				[APPTYP_ID] IN (1, 2) AND
				CDCLIENT.[DOB] BETWEEN DATEADD (YEAR, -17, sv.BEG_DATE) AND DATEADD (YEAR, -6, sv.BEG_DATE) AND
				DIAG_ID IN ('F33.0','F33.1','F33.2','F33.3','F33.9','F34.1','F43.21', '29636', '29635', '29634', '29633', '29632',
				'29631', '29630', '29626', '29625', '29624', '29623', '29622', '29621', '29620') AND CDCLDIAG.END_DATE IS NULL AND
				PAYSRC_ID = '1' 

GROUP BY CAEMP.SORT_NAME, CAEMP.ID
